# Bernoulli and Binomial Distribution - Lab

## Introduction
In this lab, you'll practice your newly gained knowledge on the Bernoulli and Binomial Distribution.

## Objectives
You will be able to:
* Apply the formulas for the Binomial and Bernoulli distribution
* Apply NumPy to randomly generate Binomial and Bernoulli trials
* Use Matplotlib to generate Binomial and Bernoulli trials with various probabilities

## Apply the formulas for the Binomial and Bernoulli distribution

When playing a game of bowling, what is the probability of throwing exactly 3 strikes in a game with 10 rounds? Assume that the probability of throwing a strike is 25% for each round. Use the formula for the Binomial distribution to get to the answer. You've created this before, so we provide you with the function for factorials again:

In [1]:
def factorial(n):
    prod = 1
    while n >= 1:
        prod = prod * n
        n = n - 1
    return prod

In [2]:
p_3_strikes = ((factorial(10))/(factorial(3)*factorial(10-3)))*((0.25)**3)*(1-0.25)**(10-3)
p_3_strikes#answer = 0.2502822

0.25028228759765625

Now, create a function for the Binomial distribution with three arguments $n$, $p$ and $k$ just like in the formula.

In [3]:
def binom_distr(n,p,k):
    result = ((factorial(n))/(factorial(k)*factorial(n-k)))*((p)**k)*(1-p)**(n-k)
    return result

Validate your previous result applying your new function.

In [4]:
binom_distr(10,0.25,3)

0.25028228759765625

Now write a for loop along with your function to compute the probability that you have five strikes or more in one game. You'll want to use numpy here!

In [5]:
import numpy as np

probability_list = []

def fill_list(k):
    for i in range(k,11):
        probability_list.append(binom_distr(10,0.25,i))
        print(probability_list)

    

In [6]:
fill_list(5)

[0.058399200439453125]
[0.058399200439453125, 0.016222000122070312]
[0.058399200439453125, 0.016222000122070312, 0.00308990478515625]
[0.058399200439453125, 0.016222000122070312, 0.00308990478515625, 0.00038623809814453125]
[0.058399200439453125, 0.016222000122070312, 0.00308990478515625, 0.00038623809814453125, 2.86102294921875e-05]
[0.058399200439453125, 0.016222000122070312, 0.00308990478515625, 0.00038623809814453125, 2.86102294921875e-05, 9.5367431640625e-07]


In [7]:
probability_array = np.array(probability_list)
probability_array

array([5.83992004e-02, 1.62220001e-02, 3.08990479e-03, 3.86238098e-04,
       2.86102295e-05, 9.53674316e-07])

In [8]:
sum(probability_array)

0.07812690734863281

In [9]:
import numpy as np
prob = 0
for i in np.arange(5,11):
     prob += binom_distr(10,0.25,i)
print(prob)

0.07812690734863281


## Use a simulation to get the probabilities for all the potential outcomes

Repeat the experiment 5000 times.

In [12]:
np.random.seed(123)


In [23]:
np.random.binomial(10, 0.25)

4

In [13]:
# leave the random seed here 
np.random.seed(123)
n = 5000
iteration = []
for loop in range(n):
    iteration.append(np.random.binomial(10, 0.25))
    np_it = np.array(iteration)



#
#
#

In [14]:
values, counts = np.unique(np_it, return_counts=True)

In [15]:
# the results should look like this:
# [0 1 2 3 4 5 6 7 8]
# [ 310  941 1368 1286  707  297   78   11    2]

values, counts = np.unique(np_it, return_counts=True)
print(values)
print(counts)

[0 1 2 3 4 5 6 7 8]
[ 310  941 1368 1286  707  297   78   11    2]


## Visualize these results

Make sure to set an appropriate title and appropriate y-axis label

In [ ]:
import matplotlib.pyplot as plt
#
#
#
#

You can see that, with a 25% strike hit rate, even when simulating 5000 times, an almost perfect and perfect game of 9 and 10 strikes didn't even occur once! If you change your seed, however, you'll see that occasionally perfect games will show up randomly. 

## Summary

Congratulations! In this lab, you practiced your newly gained knowledge on the Bernoulli and Binomial Distribution.